#!/bin/bash

cat >> /tmp/env_vars <<EOF
DEBIAN_FRONTEND=noninteractive
TZ=UTC
CDSW_USER=cdsw
CDSW_USER_ID=8536
CDSW_GROUP_ID=8536
R_VERSION=4.5.1
RSTUDIO_VERSION=2025.05.1-513
CRAN=https://cloud.r-project.org/
R_HOME=/usr/local/lib/R
R_LIBS_USER=/usr/local/lib/R/site-library
R_ENABLE_JIT=3
R_COMPILE_PKGS=1
MALLOC_ARENA_MAX=2
OMP_NUM_THREADS=1
R_MAX_VSIZE=8G
LANG=en_US.UTF-8
LC_ALL=en_US.UTF-8
EOF
